"""
Django settings for ecommerce project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os

# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# CREATE REQUIRED DIRECTORIES
# =========================================================

LOG_DIR = BASE_DIR / 'logs'

LOG_DIR.mkdir(exist_ok=True)

# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-key'
)

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.ngrok-free.app',
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
]

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = 'DENY'

# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Google Login
    'allauth.socialaccount.providers.google',

    # Local Apps
    'store',
]

# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = 'store.User'

SITE_ID = 2

# =========================================================
# AUTHENTICATION
# =========================================================

AUTHENTICATION_BACKENDS = (

    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_URL = 'store:login'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

# =========================================================
# ALLAUTH SETTINGS
# =========================================================

ACCOUNT_LOGIN_METHODS = {'email'}

ACCOUNT_SIGNUP_FIELDS = [
    'username*',
    'email*',
    'password1*',
    'password2*'
]

ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_LOGIN_ON_GET = True
# SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =========================================================
# URLS
# =========================================================

ROOT_URLCONF = 'ecommerce.urls'

# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'store.context_processors.categories_processor',

                'store.context_processors.parent_categories',

                'store.context_processors.cart_count',
            ],
        },
    },
]

# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'ecommerce.wsgi.application'

# =========================================================
# DATABASE
# =========================================================

DATABASES = {

    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Ecommerce',
        'USER': 'django_user',
        'PASSWORD': 'StrongPassword@123',
        'HOST': 'LP632\MSSQLSERVER1',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = 'static/'

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================================
# LOGGING
# =========================================================

LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'formatters': {

        'verbose': {

            'format': '{levelname} {asctime} {module} {message}',

            'style': '{',
        },

        'simple': {

            'format': '{levelname} {message}',

            'style': '{',
        },
    },

    'handlers': {

        'file': {

            'level': 'INFO',

            'class': 'logging.FileHandler',

            'filename': os.path.join(BASE_DIR, 'logs/app.log'),

            'formatter': 'verbose',
        },

        'console': {

            'class': 'logging.StreamHandler',

            'formatter': 'simple',
        },
    },

    'loggers': {

        'django': {

            'handlers': ['file', 'console'],

            'level': 'INFO',

            'propagate': True,
        },

        'store': {

            'handlers': ['file', 'console'],

            'level': 'DEBUG',

            'propagate': False,
        },
    },
}

# =========================================================
# EMAIL CONFIGURATION
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'jaspaltsingh@gmail.com'

EMAIL_HOST_PASSWORD = 'acah dpxa aran wdyd'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =========================================================
# RAZORPAY CONFIGURATION
# =========================================================

RAZORPAY_WEBHOOK_SECRET = "preetcraft_webhook_secret_2026"

# Razorpay TEST Keys

RAZORPAY_KEY_ID = "rzp_test_SiWDlv4d8mie81"

RAZORPAY_KEY_SECRET = "B4gjMraD2Dc1anrhnUaMUAXj"

# Razorpay LIVE Keys

#RAZORPAY_KEY_ID = "rzp_live_SbjiCAnOkRyFH7"

#RAZORPAY_KEY_SECRET = "2e0aVnvJ68ZJv9BgEOMOrk10"

# =========================================================
# PRODUCTION NOTES
# =========================================================

"""
Before Production:

1. Set DEBUG = False

2. Use environment variables for:
   - SECRET_KEY
   - EMAIL_HOST_PASSWORD
   - RAZORPAY KEYS
   - DATABASE PASSWORD

3. Configure proper ALLOWED_HOSTS

4. Run:
   python manage.py collectstatic

5. Use HTTPS

6. Use production database credentials
"""